
paths:
  dataset_dir: /data/Database/SPGC/baseline_data/     
  metadata_path: Hindi_M              # path to dataset containing wavs     # path to LJSpeech-style metafile with format: id|text
  dur_path: /data/Database/SPGC/baseline_data/metadata/
   
audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000
  power: 1

preprocessing:
  mel_dim_last: false # whether precomputed mels have mel channels as last dimension

model:
  lstm_dim: 512
  conv_dim: 512

durations:
  method: 'dijkstra' # options: [dijkstra, beam]

training:
  learning_rate: 0.0001
  batch_size: 60
  epochs: 800
  plot_steps: 1000
  checkpoint_steps: 10_000
